### ISSUE TITLE
Add ability to configure binary paths for social image generation

### ISSUE THREAD

**Issue by marcorieser** [studio1902/statamic-peak-seo#20]
In my local environment `node` and `npm` is installed via `nvm`. Therefore php / Browsershot can not resolve the binaries to generate the social images. Spatie gives us the ability to pass custom paths to those binaries (https://spatie.be/docs/browsershot/v2/requirements#content-custom-node-and-npm-binaries) but this is currently not possible with the addon. Oh if only someone could implement this.

**Comment by robdekort** [comment]
Fixed in #19
