### ISSUE TITLE
Error when installed on fresh statamic install

### ISSUE THREAD

**Issue by AndreasSchantl** [studio1902/statamic-peak-seo#8]
**Describe the bug**
The package does not include the common fieldset which the fieldsets are referencing to, causing an error.

A simple solution would be to include it as part of the package.

**Comment by robdekort** [comment]
That file is available in Peak. You need it to use the addon I'm afraid.

**Comment by AndreasSchantl** [comment]
I know. I fixed that already. I just wanted to open the issue to make aware that it is not included with this package. 

I wonder if we could check for it and publish the file if it's not existent. It would make the package more user friendly in case someone uses only the SEO package.

**Comment by robdekort** [comment]
Gotcha. I don't think the file belongs in there though. 

I'm currently not interested in supporting that use case I'm afraid.
